### ISSUE TITLE
Request: allow guest login on PC to be able to add to library, just like on Android

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-shell#110]
On Android it's possible, but on PC you can't.

[2019-12-23_00-10-36.zip](https://github.com/Stremio/stremio-shell/files/3993060/2019-12-23_00-10-36.zip)

Please make them both allow to add to library, with or without an account.

**Comment by Ivshti** [comment]
The intended behavior is to not allow items to be added to the library without an account - because without an account, the library won't be persisted. Back when we allowed it, we had plenty of users who were complaining that they lost their library, who didn't have an account.

**Comment by AndroidDeveloperLB** [comment]
This doesn't make sense.
Instead of forcing users to register, you should write the benefits of it: be able to have the library on the cloud, so that you will always be able to return to it, even if you switch to a new PC.

You have it on Android. Why not on PC ? I'd actually think that PC users are "smarter" in this case than of Android users...
Why instead of being informative you chose to be restrictive?
At least have this option as a bit hidden, and explain the disadvantages.

**Comment by Ivshti** [comment]
Thanks for the feedback

This is a screenshot from the Library on the desktop.

We think it explains the advantages - let us know if you can think of any ways to make that better.

Regarding why the Android is different: because we haven't implemented the restriction - not because we've decided it. 

Anyway, we've experimented with this before, and we've tried explaining the advantages of signing up while still allowing items to be added to the library - it didn't work, we still got a lot of "I lost my library" complaints.

![Screenshot_2019-12-24 Stremio - All you can watch ](https://user-images.githubusercontent.com/1247629/71421932-06c82d80-2676-11ea-8b7c-930c199ed307.png)

**Comment by AndroidDeveloperLB** [comment]
Please add a way to use it without sign in. You can show a warning below the button to do it, that will say that it might be lost if switching to a new PC, or something. 
As for Android, please don't add this restriction there too.
Android already has a way to backup data of apps (usually using a simple manifest flag), including both preferences and DB files. There is no need to sign in for it. Sign in could be useful if you use both Android and PC app, so that they will be in sync. It isn't needed for data recovery.
