### ISSUE TITLE
Bug: using guest login, it asks to get an account again after next run of the app

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-shell#252]
On v4.4.142, when I choose to use a guest account, next time I start the app it asks me again to login to an account:

![image](https://user-images.githubusercontent.com/5357526/128246670-afac83b9-27b0-457e-886e-d66175ae3fe6.png)

Again and again.

Please fix this.
I don't want a real account. I don't need it.

**Comment by jaruba** [comment]
@AndroidDeveloperLB

How is this a bug? If you want your session to persist, you will need to make an actual account, if you are a guest your session will not persist.

So either make an account for it to persist the session, or click "Sing Up With Email" and "Guest Login" again the next time you start the app.

These 2 parts of what you say are contradictory:
> next time I start the app it asks me again to login to an account
> Again and again

and:

> I don't want a real account. I don't need it.

Because if you want it to not ask you to login again, you DO need an account.

**Comment by AndroidDeveloperLB** [comment]
@jaruba Why did you close this without letting me reply first? 
:(

**Comment by jaruba** [comment]
> I don't want to be asked again to login. I want it to auto-login the next times I launch the app.

Auto-login to what? You need an account to auto-login.

> Imagine Gmail would ask you to login to your account each time you open Chrome.

For Gmail you actually do have an account though, right? You'll need one for Stremio too in order to do that.

> I don't need a real account. I'm fine with a guest account.

"Real account" is the only account, there is no such thing as a "guest account", it's a guest session.

This is not debatable, and it's not a bug.

**Comment by AndroidDeveloperLB** [comment]
@jaruba I don't want to have an account. I want to use the app as it is. Locally.

As for Gmail, I don't think you understood the example. Each time I enter Chrome and reach Gmail there, I don't need to login myself. It auto-logins. It doesn't ask me over and over to login. Once was enough to ask me. 

Here it asks me over and over. I don't want that. It's a really annoying thing. 
So it's a bug because it already asked me to login, and I chose to have a guest login. That's what I want to have all the time. 

Please fix this issue.
Guest login is enough for me. I don't want to subscribe to anything. It worked in the past fine without asking me all the time. 
Using everything on the PC, locally, is enough for me.

**Comment by AndroidDeveloperLB** [comment]
@jaruba It's possible to do it on Android version of Stremio, so why shouldn't it be possible on PC too?

**Comment by stellarpower** [comment]
For me, there's a difference between wanting the app to remember my preference, and wanting to have an account that is linked across devices and in the cloud, where my data is sent to a remote server.

Personally, I would like to sign in as a guest, and to do this automatically upon each startup - a CLI flag to sign in as a guest automatically would in a sense, achieve the same thing. I am often doing other things when I bring up Stremio, so it's a couple of keypresses I don't need to make afresh each time. And furthermore, I think it'd be possible to have the application resume where it left off, but only for the current user on the local machine, without needing an online account. Previous searches and addons are also kept, so the idea of opening back up to the last episode being played/etc. makes sense to me as a future option and would enhance the user experience for me.

And as mentioned, this behaviour does exist already in the Android version of the app.
