### ISSUE TITLE
Steps to build stremio on Mac 

### ISSUE THREAD

**Issue by kata62** [Stremio/stremio-shell#262]
1.	$ brew install qt@5
	2.	brew install openssl 
	3.	Brew install mpv 
	4.	Git clone — recursive https://github.com/Stremio/stremio-  shell.git
	5.	Cd stremio-shell 
	6.	qmake 
	7.	Make 
	8.   info.plist to be modified for values ${MACOSX_BUNDLE_EXECUTABLE_NAME}    
	${MACOSX_BUNDLE_GUI_IDENTIFIER}  ${MACOSX_BUNDLE_BUNDLE_VERSION}
	8.	Sh ~/stremio-shell/Mac/finalize.sh
Any comments will be appreciated

**Comment by core1024** [comment]
Perhaps the MacOS build instructions are a bit outdated. We currently use MPV binaries from iina project. Also we switched to the CMake build system. Several environment variables must be set in order to build the shell. You can see the building steps from our CI script [here](https://github.com/Stremio/stremio-shell/blob/560db3ece2f1de6c8840a29d879795a233faa7d5/.github/workflows/shell.yaml).
We use Qt 5.15.2 from the official release but I presume the brew version will also be fine. The `qtwebengine` and `qtwebglplugin` modules are must. The shell will compile without them but it will crash in runtime if they are missing. After you comile the code you need to run `macdeployqt`.
If you execute all the steps to the `Testdrive` step. You'll have a working shell app bundle. The rest of the steps are for signing and packing the DMG.
