### ISSUE TITLE
Screen on Arch Linux keeps dimming due to inactivity while watching

### ISSUE THREAD

**Issue by IgnusG** [Stremio/stremio-shell#64]
### What is the problem?

The screen keeps turning off while watching as neither the mouse nor the keyboard is in use. Other applications like chrome are able to prevent dimming the screen if a video is playing. 

### What did I expect?

Streamio should block power management and prevent the screen from dimming while watching.

**Comment by IgnusG** [comment]
An addition, If I’m playing a video in chrome KDE (which I’m using) displays a message in the power management widget: 
```
An application is blocking power management: Google Chrome
Reason: Playing video
```
While using stremio this isn’t displayed. 

PS: Also occurred on Arch Gnome “flavor”. 

PPS: Cool, first time ive seen this issue Migration on GitHub. Really nice feature

**Comment by oswaldoleal** [comment]
This issue also appears on Ubuntu 19.04/19.10

**Comment by gnomo223** [comment]
And in Solus OS to, but not on my Win10 machine

**Comment by cleversonahum** [comment]
An alternative solution, which has worked for me in Manjaro Linux, is use [caffeine](https://github.com/caffeine-ng/caffeine-ng)

**Comment by victorgveloso** [comment]
It is not fixed yet (see https://github.com/Stremio/stremio-shell/pull/173#issuecomment-750523915). 

I've just tested on a fresh install of Arch Linux with plasma. And I'm pretty sure this bug persists. Please @Ivshti reopen the issue.

obs: another bug report is available at https://github.com/Stremio/stremio-bugs/issues/228 which one should I follow?

**Comment by Ivshti** [comment]
Sorry but even if it's not fixed, the dbus patch already fixes a lot of the cases of this bug, and chasing bugs on specific linux distros is not something we can afford to do at the moment - we don't have the time/bandwidth to do it

**Comment by victorgveloso** [comment]
I'm trying to debug the issue, cloning the repo and compiling with the cmd `build-package.sh ArchLinux`. I've already found some bugs in the process (related to recent changes on arch build system), but if I manage to solve it I'll make a PR. 

Btw, I only asked for the issue reopening. I'm not asking you to solve the problem it reports. It is not fair to pretend the issue was solved just because you don't intend to put more effort on it. 

Finally I have three arguments that support my POV: 

- this issue explicitly reports a bug on Arch Linux distro and ~35% of their users adopt plasma as the main DE (see https://i.redd.it/jvgrxwm9w5461.png)
- Arch Linux is one of the 5 supported linux distros (https://github.com/Stremio/stremio-shell/tree/master/distros, https://github.com/Stremio/stremio-shell/blob/master/DEBIAN.md, https://github.com/Stremio/stremio-shell/blob/master/OpenSuseLeap.md) and OpenSuseLeap is another supported distro whose main DE is plasma.
- Stremio-shell's UI is built with Qt Framework. And the main desktop environment based on Qt is plasma. Supporting any other DE over plasma is the worst choice you could made.

**Comment by Ivshti** [comment]
Ok fair enough, if you're willing to help then it makes sense to reopen

**Comment by victorgveloso** [comment]
I really appreciate your decision. Thank you.

**Comment by victorgveloso** [comment]
I've managed to build stremio from master branch and it miraculously fixed the problem I had. 

It seems that the latest stable release does not include the modifications from the PR 173. Fortunately this was not a waste of our time, because I created a PR (#198)  that fixes the docker build for archlinux. It ain't much, but it is honest work.

A build for ArchLinux with the fix is available at: [stremio-4.4.120-1.zip](https://github.com/Stremio/stremio-shell/files/6010258/stremio-4.4.120-1.zip)

**Comment by core1024** [comment]
My advice for ArchLinux users is to install Stremio from [AUR](https://aur.archlinux.org/packages/stremio-beta). This is our official and supported package. We will soon release a new version and if you use AUR helper like yay or paru you will recveive automatic update.

**Comment by Ivshti** [comment]
In this case I'm happy to close this again :D
